services:
  # FastAPI
  api:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: epic-database-api
    env_file:
      - ./backend/app/.env.local
      #- ./backend/app/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/
    command: "--reload"
    healthcheck:
      test: ["CMD-SHELL", "curl -XGET http://localhost:8000/health/check || exit 1"]
      interval: 60s
      timeout: 20s
      retries: 3
      start_period: 30s
    depends_on:
      mysql:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Next.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: epic-database-frontend
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy

  # FastAPI
  subscriber:
    build:
      context: ./backend/app
      dockerfile: Dockerfile.subscriber
    container_name: epic-database-subscriber
    env_file:
      - ./backend/app/.env.local
      #- ./backend/app/.env
    volumes:
      - ./backend/app:/app/
    ports:
      - "8001:8000"
    command: "--reload"
    depends_on:
      api:
        condition: service_healthy
      mysql:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # MySQL
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: epic-database-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=epicdatabase
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/mysql/conf.d:/etc/mysql/conf.d
      - epic-database-mysql-volume:/var/lib/mysql
    tty: true
    healthcheck:
      # MySQL が起動しているか確認するための設定
      test: mysqladmin ping -h 127.0.0.1 -u$$DATABASE_USERNAME -p$$DATABASE_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Postgresql
  postgresql:
    image: postgres:14
    platform: linux/x86_64
    container_name: epic-database-postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=epicdatabase
      - TZ=Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - epic-database-postgresql-volume:/var/lib/postgresql
    tty: true
    healthcheck:
      # Postgresql が起動しているか確認するための設定
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis
  redis:
    image: redis:7.4
    platform: linux/x86_64
    container_name: epic-database-redis
    ports:
      - "6379:6379"
    volumes:
      - epic-database-redis-volume:/data
    tty: true
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Mail Server
  mailhog:
    image: mailhog/mailhog
    container_name: epic-database-mailhog
    ports:
      - "8025:8025"

volumes:
  # MySQL
  epic-database-mysql-volume:
    driver: 'local'
  # Postgresql
  epic-database-postgresql-volume:
    driver: 'local'
  epic-database-redis-volume:
    driver: 'local'

networks:
  api-services:
    external: true
