services:
  # App
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epic-datahub
    env_file:
      - .env.local
      #- .env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app/
    command: "--reload"
    depends_on:
      mysql:
        condition: service_healthy
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # MySQL
  mysql:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: epic-datahub-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=epic-datahub
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./infrastructure/mysql/conf.d:/etc/mysql/conf.d
      - epic-datahub-mysql-volume:/var/lib/mysql
    tty: true
    healthcheck:
      # MySQL が起動しているか確認するための設定
      test: mysqladmin ping -h 127.0.0.1 -u$$DATABASE_USERNAME -p$$DATABASE_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Postgresql
  postgresql:
    image: postgres:14
    platform: linux/x86_64
    container_name: epic-datahub-postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=epic-datahub
      - TZ=Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - epic-datahub-postgresql-volume:/var/lib/postgresql
    tty: true
    healthcheck:
      # Postgresql が起動しているか確認するための設定
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis
  redis:
    image: redis:7.4
    platform: linux/x86_64
    container_name: epic-datahub-redis
    ports:
      - "6379:6379"
    volumes:
      - epic-datahub-redis-volume:/data
    tty: true
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 3

  # Mail Server
  mailhog:
    image: mailhog/mailhog
    container_name: epic-datahub-mailhog
    ports:
      - "8025:8025"

volumes:
  # MySQL
  epic-datahub-mysql-volume:
    driver: 'local'
  # Postgresql
  epic-datahub-postgresql-volume:
    driver: 'local'
  epic-datahub-redis-volume:
    driver: 'local'

networks:
  api-services:
    external: true
