name: _python-test

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: false
        default: '3.12'

jobs:
  test:
      runs-on: ubuntu-latest
      name: "テスト"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ inputs.python-version }}
        - name: Run Python Test
          run: |
            pip install -r ./backend/requirements.txt
            pip install -r ./test/requirements.txt
            pytest ./test

# NOTE: pytest ./test/unit を実行すると循環参照エラーが発生するため、上記のジョブに変更

#  unit-test:
#    runs-on: ubuntu-latest
#    name: "ユニットテスト"
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ inputs.python-version }}
#      - name: Run Unit Test
#        run: |
#          pip install -r ./app/requirements.txt
#          pip install -r ./test/requirements.txt
#          pytest ./test/unit
#  acceptance-test:
#    runs-on: ubuntu-latest
#    name: "受け入れテスト"
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ inputs.python-version }}
#      - name: Run Acceptance Test
#        run: |
#          pip install -r ./app/requirements.txt
#          pip install -r ./test/requirements.txt
#          pytest ./test/acceptance
