name: _python-test

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        required: false
        default: '3.12'

jobs:
  test:
      runs-on: ubuntu-latest
      name: "テスト"
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: ${{ inputs.python-version }}
        - name: Run Python Test
          run: |
            pip install -r ./app/requirements.txt
            pip install -r ./test/requirements.txt
            pytest ./test --cov=./app --junitxml=pytest.xml --cov-report=term-missing:skip-covered | tee pytest-coverage.txt
        - name: Create Coverage Comment
          id: coverageComment
          uses: MishaKav/pytest-coverage-comment@main
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            pytest-coverage-path: pytest-coverage.txt
            junitxml-path: ./pytest.xml
        - name: Create Coverage Badge
          uses: schneegans/dynamic-badges-action@v1.7.0
          with:
            auth: ${{ secrets.BADGE_GIST }}
            gistID: d6078b30894e7b3b786d38a023de5334
            filename: pytest-coverage-comment.json
            label: Coverage
            message: ${{ steps.coverageComment.outputs.coverage }}
            color: ${{ steps.coverageComment.outputs.color }}
            namedLogo: python
            forceUpdate: true

# NOTE: pytest ./test/unit を実行すると循環参照エラーが発生するため、上記のジョブに変更

#  unit-test:
#    runs-on: ubuntu-latest
#    name: "ユニットテスト"
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ inputs.python-version }}
#      - name: Run Unit Test
#        run: |
#          pip install -r ./app/requirements.txt
#          pip install -r ./test/requirements.txt
#          pytest ./test/unit
#  acceptance-test:
#    runs-on: ubuntu-latest
#    name: "受け入れテスト"
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v4
#        with:
#          fetch-depth: 0
#      - name: Set up Python
#        uses: actions/setup-python@v5
#        with:
#          python-version: ${{ inputs.python-version }}
#      - name: Run Acceptance Test
#        run: |
#          pip install -r ./app/requirements.txt
#          pip install -r ./test/requirements.txt
#          pytest ./test/acceptance
